name: Update dependencies & pre-commits

on:
  schedule:
    - cron: '0 0 * * 1' # every Monday at 00:00
  workflow_dispatch:

jobs:
  seria:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update dependencies & pre-commits
        uses: seriaati/update-deps@main
        