name: create-release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Save current tag name
        run: |
          echo "GITHUB_REF_NAME<<EOF" >> $GITHUB_OUTPUT
          echo "$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash
        id: save-tag
      - name: Delete current local and remote tag
        run: |
          git tag -d $GITHUB_REF_NAME
          git push --delete origin $GITHUB_REF_NAME
      - name: Update version number
        run: |
          OLD_VERSION=`cat pyproject.toml | grep ^version | cut -d '"' -f 2`
          OLD_VERSION="\"$OLD_VERSION\""
          NEW_VERSION="\"${{ steps.save-tag.outputs.GITHUB_REF_NAME  }} \""
          NEW_VERSION_WITHOUT_V=`echo $NEW_VERSION | cut -c 2-`
          sed -i "s+version = $OLD_VERSION+version = $NEW_VERSION_WITHOUT_V+g" pyproject.toml
        shell: bash
        id: update-version
      - name: Commit and push the changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore(ver): Bump version number to ${{ steps.save-tag.outputs.GITHUB_REF_NAME }}"
          add: "pyproject.toml"
          default_author: github_actions
          tag: ${{ steps.save-tag.outputs.GITHUB_REF_NAME }}
          push: true
      - name: Generate changelog
        uses: tj-actions/git-cliff@v1
        with:
          template-config: https://raw.githubusercontent.com/seriaati/seria-library/main/cliff-template.toml
          args: --latest --strip header
        id: git-cliff
      - name: Get changelog content
        run: |
          echo "content<<EOF" >>$GITHUB_OUTPUT
          cat "HISTORY.md" >>$GITHUB_OUTPUT
          echo "EOF" >>$GITHUB_OUTPUT
        shell: bash
        id: get-content
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.get-content.outputs.content }}