name: Create release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        id: save-tag
      - name: Compare remote and local versions
        run: |
          REMOTE_VERSION=`echo $(git describe --tags --abbrev=0) | cut -c 2-`
          LOCAL_VERSION=`cat pyproject.toml | grep ^version | cut -d '"' -f 2`
          echo $REMOTE_VERSION
          echo $LOCAL_VERSION
          if [ "$REMOTE_VERSION" = "$LOCAL_VERSION" ]; then
            echo "Versions are same"
            exit 0
          fi
          echo "LOCAL_VERSION<<EOF" >> $GITHUB_OUTPUT
          echo "$LOCAL_VERSION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash
        id: compare-versions
      - name: Create tag locally
        if: steps.compare-versions.outputs.LOCAL_VERSION != ''
        run: |
          git tag v${{ steps.compare-versions.outputs.LOCAL_VERSION }}
        id: create-tag
      - name: Generate changelog
        if: steps.compare-versions.outputs.LOCAL_VERSION != ''
        uses: tj-actions/git-cliff@v1
        with:
          template-config: https://raw.githubusercontent.com/seriaati/seria-library/main/cliff-template.toml
          args: --latest --strip header
        id: git-cliff
      - name: Get changelog content
        if: steps.compare-versions.outputs.LOCAL_VERSION != '' 
        run: |
          echo "content<<EOF" >>$GITHUB_OUTPUT
          cat "HISTORY.md" >>$GITHUB_OUTPUT
          echo "EOF" >>$GITHUB_OUTPUT
        shell: bash
        id: get-content
      - name: Create Release
        if: steps.compare-versions.outputs.LOCAL_VERSION != ''
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          body: ${{ steps.get-content.outputs.content }}
          tag_name: v${{ steps.compare-versions.outputs.LOCAL_VERSION }}