name: create-release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate changelog with git-cliff
        uses: tj-actions/git-cliff@v1
        with:
          template-config: https://raw.githubusercontent.com/seriaati/seria-library/main/cliff-template.toml
          args: --latest --strip header
        id: git-cliff
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.git-cliff.outputs.content }}