name: main

on:
  schedule:
    - cron: '0 0 * * 1' # every Monday at 00:00
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update dependencies & pre-commits
        uses: seriaati/update-deps
      - name: Create release
        uses: seriaati/create-release